<a href="https://colab.research.google.com/github/Vineeth-19/dsProject/blob/main/Day07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

In [3]:
data =pd.read_csv('https://talentcocomedia.s3.amazonaws.com/ml-assets/heart-disease.csv')

In [4]:
y = data['target']

In [5]:
x = data.drop('target', axis =1)

In [6]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)

In [7]:
x_train.shape , x_test.shape , y_train.shape , y_test.shape

((212, 13), (91, 13), (212,), (91,))

Logistic Regression


In [8]:
from sklearn.linear_model import LogisticRegression
model_lr = LogisticRegression(penalty ='l2' , solver ='newton-cg',C=5)

In [9]:
model_lr.fit(x_train,y_train)

LogisticRegression(C=5, solver='newton-cg')

In [10]:
yPredLr = model_lr.predict(x_test)

In [11]:
yPredLr

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0])

 Accuracy Of Logistic Regression


In [12]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(yPredLr , y_test)
acc


0.8461538461538461

sklearn.neighbors.KNeighborsClassifier

In [13]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [14]:
yPredKnn = neigh.predict(x_test)

In [15]:
yPredKnn

array([0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0])

 Accuracy of KNN

In [16]:
accKnn = accuracy_score(yPredKnn , y_test)

In [17]:
accKnn

0.6703296703296703

Decision Tree Classifier

In [18]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)

DecisionTreeClassifier()

In [19]:
yPredDtc = dtc.predict(x_test)

In [20]:
yPredDtc

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0])

Accuracy of Decision Tree Classifier

In [21]:
accDtc = accuracy_score(yPredDtc , y_test)

In [22]:
accDtc

0.7362637362637363

Grid Search

In [23]:
from sklearn.model_selection import GridSearchCV
model = LogisticRegression(penalty ='l2')

val = list(np.arange(0.01,1,0.1))

parameters = {'solver':('newton-cg', 'liblinear','sag','saga'),'C':val}

clf_lr = GridSearchCV(model,parameters)
clf_lr.fit(x_train,y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means 

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [0.01, 0.11, 0.21000000000000002,
                               0.31000000000000005, 0.41000000000000003, 0.51,
                               0.6100000000000001, 0.7100000000000001, 0.81,
                               0.91],
                         'solver': ('newton-cg', 'liblinear', 'sag', 'saga')})

In [24]:
clf_lr.best_params_

{'C': 0.7100000000000001, 'solver': 'liblinear'}

In [25]:
test_pred = clf_lr.predict(x_test)

In [26]:
accClfLr = accuracy_score(test_pred,y_test)

In [27]:
accClfLr

0.8461538461538461

Accuracy of Logistic Regression

In [55]:
yPredLr = clf_lr.predict(x_test)

In [56]:
accLr = accuracy_score(yPredLr , y_test)

In [57]:
accLr

0.8461538461538461

Grid Search For KNN

In [43]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

# Create a KNN classifier
knn = KNeighborsClassifier()

# Define the parameter values that should be searched
k_range = list(np.arange(1,30,1))
param_grid = dict(n_neighbors=k_range)

# Instantiate the grid search model
grid = GridSearchCV(knn, param_grid)

# Fit the grid search model to the data
grid.fit(x_train, y_train)

# View the results
print(grid.best_score_)
print(grid.best_params_)



0.6703211517165005
{'n_neighbors': 22}


Accuracy Of KNN

In [44]:
gPredKnn = grid.predict(x_test)

In [45]:
gAccKnn = accuracy_score(gPredKnn,y_test)

In [46]:
gAccKnn

0.6923076923076923

Grid Search For Dtree Classifier

In [51]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier

# Create a decision tree classifier
dtree = DecisionTreeClassifier()

# Define the parameter values that should be searched
max_depth = list(range(1, 11))
min_samples_split = [2, 3, 4, 5]
min_samples_leaf = [1, 2, 3]
criterion = ['gini', 'entropy']
param_grid_dtree = dict(max_depth=max_depth, min_samples_split=min_samples_split, 
                  min_samples_leaf=min_samples_leaf, criterion=criterion)

# Instantiate the grid search model
grid_dtree = GridSearchCV(dtree, param_grid_dtree, cv=10, scoring='accuracy')

# Fit the grid search model to the data
grid_dtree.fit(x_train, y_train)

# View the results
print(grid_dtree.best_score_)
print(grid_dtree.best_params_)


0.7783549783549784
{'criterion': 'gini', 'max_depth': 6, 'min_samples_leaf': 1, 'min_samples_split': 4}


Accuracy of Dtree Classifier

In [52]:
gPredDtree = grid_dtree.predict(x_test)

In [53]:
accGDtree = accuracy_score(gPredDtree,y_test)

In [54]:
accGDtree

0.7252747252747253

Confusion Matrix for Logistic regression

In [58]:
from sklearn.metrics import confusion_matrix
confusion_matrix(yPredLr,y_test)

array([[41,  7],
       [ 7, 36]])

In [59]:
from sklearn.metrics import classification_report

print(classification_report(y_test, yPredLr))

              precision    recall  f1-score   support

           0       0.85      0.85      0.85        48
           1       0.84      0.84      0.84        43

    accuracy                           0.85        91
   macro avg       0.85      0.85      0.85        91
weighted avg       0.85      0.85      0.85        91



Confusion Matrix For KNN

In [60]:
from sklearn.metrics import confusion_matrix
confusion_matrix(gPredKnn,y_test)

array([[33, 13],
       [15, 30]])

In [61]:
from sklearn.metrics import classification_report

print(classification_report(y_test, gPredKnn))

              precision    recall  f1-score   support

           0       0.72      0.69      0.70        48
           1       0.67      0.70      0.68        43

    accuracy                           0.69        91
   macro avg       0.69      0.69      0.69        91
weighted avg       0.69      0.69      0.69        91



Confusion Matrix For Dtree

In [62]:
from sklearn.metrics import confusion_matrix
confusion_matrix(gPredDtree,y_test)

array([[35, 12],
       [13, 31]])

In [63]:
from sklearn.metrics import classification_report

print(classification_report(y_test, gPredDtree))

              precision    recall  f1-score   support

           0       0.74      0.73      0.74        48
           1       0.70      0.72      0.71        43

    accuracy                           0.73        91
   macro avg       0.72      0.73      0.72        91
weighted avg       0.73      0.73      0.73        91

